---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy
  labels:
     app: httpd

spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd

  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd-ctr
        image: httpd
        ports:
        - containerPort: 80