---
apiVersion: v1
kind: Service
metadata:
  name: httpd-lb
  labels:
     app: httpd

spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP 
  selector:
    app: httpd